//JavaScript code generated by API++
//API++ by Piccolowen
window.onload = apifunc();
async function apifunc() {
const url = 'https://api.github.com/repos/piccolowen/apipp';
const response = await fetch(url);
const result = await response.json();
const apiresult = document.getElementById('repo');
console.log('api++ system working...')
console.log('api++ system by Piccolowen https://github.com/Piccolowen')
console.log('api++ result:');
console.log(result);
console.log('name result: ' + result.name)
const title = document.createElement('a')
title.href = result.html_url
title.target = '_blank'
title.className = 'repo-title'
title.textContent = result.name
apiresult.appendChild(title)
console.log('full name result: ' + result.full_name)
const fullname = document.createElement('p')
fullname.className = 'repo-fullname'
fullname.textContent = result.full_name
apiresult.appendChild(fullname)
console.log('desc result: ' + result.description)
const desc = document.createElement('p')
desc.className = 'repo-desc'
desc.textContent = result.description
apiresult.appendChild(desc)
}
