//JavaScript code generated by API++
//API++ by Piccolowen
window.onload = apifunc();
async function apifunc() {
const url = 'https://api.github.com/repos/piccolowen/apipp';
const response = await fetch(url);
const result = await response.json();
const apiresult = document.getElementById('title');
console.log('API++ system working...')
console.log('API++ system by Piccolowen https://github.com/Piccolowen')
console.log('desc result: ' + result.description)
const desc = document.createElement('title')
desc.className = 'pagetitle'
desc.textContent = "API++: " + result.description
apiresult.appendChild(desc)
}