//JavaScript code generated by API++
//API++ by Piccolowen
window.onload = apifunc();
async function apifunc() {
const url = 'https://api.github.com/repos/piccolowen/apipp';
const response = await fetch(url);
const result = await response.json();
const apiresult = document.getElementById('apippdesc');
console.log('api++ system working...')
console.log('api++ system by Piccolowen https://github.com/Piccolowen')
console.log('api++ result:');
console.log(result);
console.log('desc result: ' + result.description)
const desc = document.createElement('p')
desc.className = 'apippdesc'
desc.textContent = "API++: " + result.description
apiresult.appendChild(desc)
}
